version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    container_name: clinica-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: Clinica
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '1234'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clinica-app
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - '8080:8080'
    environment:
      # mantém encoding
      - JAVA_OPTS=-Dfile.encoding=UTF-8
      # (opcional) variáveis para seu código ler, caso você adapte ConexaoBD
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=Clinica
      - DB_USER=postgres
      - DB_PASSWORD=1234

volumes:
  postgres-data:
